name: insightsolver-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pandas=2.2.2
  - numpy=2.0.0
  - requests=2.32.3
  - jsonpickle=3.2.1
  - google-auth=2.6.0
  - cryptography=43.0.0
  - mpmath=1.3.0
  - pip
  - pip:
    - idna>=2.10
    - urllib3>=2.0.2
    - google-auth-oauthlib==1.2.0
    - google-auth-httplib2==0.2.0